// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cktbtbpyiqvgadseulpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrdGJ0YnB5aXF2Z2Fkc2V1bHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExMDY5OTEsImV4cCI6MjA4NjY4Mjk5MX0.YJfZ4y3UaTkcO0bnNdjYgZ-dNJ0u4jlK5zJxOxLUql0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});